# Generated by Django 3.2.14 on 2022-08-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='author',
        ),
    ]
