# Generated by Django 3.2.14 on 2022-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_description_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.TextField(default='date'),
        ),
    ]
