# Generated by Django 4.1 on 2022-08-19 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('article', models.TextField()),
                ('comment', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('is_reply_to', models.IntegerField(default=None)),
            ],
        ),
    ]
