# Generated by Django 4.1 on 2022-08-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reply_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
