# Generated by Django 4.1 on 2022-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
