# Generated by Django 3.2.14 on 2022-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('comment', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
